name: Build Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build
